In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat) # cast list to numpy array or matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10,4) # third argument is step size

array([0, 4, 8])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(0,5,100) # third argument is number of points

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [9]:
np.eye(4) # returns identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
 np.random.rand() # uniform distribution (0-1)

0.574532153528076

In [11]:
np.random.rand(5,5)

array([[0.2754324 , 0.61679766, 0.68303937, 0.26694452, 0.04774416],
       [0.79796309, 0.04621649, 0.09270781, 0.17688918, 0.72854915],
       [0.90801644, 0.13219033, 0.59432449, 0.75698456, 0.24596969],
       [0.87141709, 0.19450639, 0.58967629, 0.36007816, 0.7267191 ],
       [0.73203157, 0.78807775, 0.23486978, 0.42191211, 0.60398279]])

In [12]:
np.random.randn(5) # normal distribution

array([ 0.60985437, -1.46155083, -1.17681172, -0.63504144,  0.20762287])

In [13]:
np.random.randint(0,5,10) # random integer with interval and number of instances

array([0, 1, 3, 2, 0, 3, 0, 2, 4, 1])

In [14]:
arr = np.arange(25)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
ranarr = np.random.randint(0,50,10)

In [17]:
ranarr

array([14, 38, 30, 43, 35, 21, 37,  0,  5, 47])

In [18]:
arr.reshape(5,5) # must match the original number of digits

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ranarr.max()

47

In [20]:
ranarr.min()

0

In [21]:
ranarr.argmax() # index location of max value

9

In [22]:
ranarr.argmin()

7

In [23]:
arr.shape # not a function - it returns an attribute - no parentheses

(25,)

In [24]:
arr = arr.reshape(5,5)

In [25]:
arr.shape

(5, 5)

In [26]:
arr.dtype

dtype('int64')

Indexing and selection - slice notation

In [28]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[8]

8

In [30]:
arr[1:5]

array([1, 2, 3, 4])

In [31]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [32]:
arr[:6] # all up to idx 6

array([0, 1, 2, 3, 4, 5])

In [33]:
arr[4:] # all beyond idx 4

array([4, 5, 6, 7, 8, 9])

Broadcast

In [34]:
arr[0:5] = 100 # broadcast value to the first four digits
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [36]:
arr = np.arange(0,10)

In [40]:
sliceArr = arr[0:6] # this is not a copy of arr. It is a reference.

In [41]:
sliceArr[:]

array([0, 1, 2, 3, 4, 5])

In [42]:
sliceArr[:] = 90

In [43]:
sliceArr

array([90, 90, 90, 90, 90, 90])

In [44]:
arr # changing sliceArr also changes arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9])

In [45]:
# if you want a copy
arr_copy = arr.copy() # must use copy method explicitly

In [46]:
arr_copy[:] = 100 # broadcasting

In [47]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [48]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9])