In [2]:
import numpy as np

In [3]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat) # cast list to numpy array or matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.arange(0,10,4) # third argument is step size

array([0, 4, 8])

In [6]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.linspace(0,5,100) # third argument is number of points

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [9]:
np.eye(4) # returns identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
 np.random.rand() # uniform distribution (0-1)

0.574532153528076

In [11]:
np.random.rand(5,5)

array([[0.2754324 , 0.61679766, 0.68303937, 0.26694452, 0.04774416],
       [0.79796309, 0.04621649, 0.09270781, 0.17688918, 0.72854915],
       [0.90801644, 0.13219033, 0.59432449, 0.75698456, 0.24596969],
       [0.87141709, 0.19450639, 0.58967629, 0.36007816, 0.7267191 ],
       [0.73203157, 0.78807775, 0.23486978, 0.42191211, 0.60398279]])

In [12]:
np.random.randn(5) # normal distribution

array([ 0.60985437, -1.46155083, -1.17681172, -0.63504144,  0.20762287])

In [13]:
np.random.randint(0,5,10) # random integer with interval and number of instances

array([0, 1, 3, 2, 0, 3, 0, 2, 4, 1])

In [14]:
arr = np.arange(25)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
ranarr = np.random.randint(0,50,10)

In [17]:
ranarr

array([14, 38, 30, 43, 35, 21, 37,  0,  5, 47])

In [18]:
arr.reshape(5,5) # must match the original number of digits

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
ranarr.max()

47

In [20]:
ranarr.min()

0

In [21]:
ranarr.argmax() # index location of max value

9

In [22]:
ranarr.argmin()

7

In [23]:
arr.shape # not a function - it returns an attribute - no parentheses

(25,)

In [24]:
arr = arr.reshape(5,5)

In [25]:
arr.shape

(5, 5)

In [26]:
arr.dtype

dtype('int64')

Indexing and selection - slice notation

In [28]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[8]

8

In [30]:
arr[1:5]

array([1, 2, 3, 4])

In [31]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [32]:
arr[:6] # all up to idx 6

array([0, 1, 2, 3, 4, 5])

In [33]:
arr[4:] # all beyond idx 4

array([4, 5, 6, 7, 8, 9])

Broadcast

In [34]:
arr[0:5] = 100 # broadcast value to the first four digits
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [36]:
arr = np.arange(0,10)

In [40]:
sliceArr = arr[0:6] # this is not a copy of arr. It is a reference.

In [41]:
sliceArr[:]

array([0, 1, 2, 3, 4, 5])

In [42]:
sliceArr[:] = 90

In [43]:
sliceArr

array([90, 90, 90, 90, 90, 90])

In [44]:
arr # changing sliceArr also changes arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9])

In [45]:
# if you want a copy
arr_copy = arr.copy() # must use copy method explicitly

In [46]:
arr_copy[:] = 100 # broadcasting

In [47]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [48]:
arr

array([90, 90, 90, 90, 90, 90,  6,  7,  8,  9])

In [49]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [50]:
# double bracket format to grap digits
arr_2d[0][0]

5

In [51]:
arr_2d[0]

array([ 5, 10, 15])

In [52]:
arr_2d[1][1]

25

In [53]:
# comma notation
arr_2d[2,1]

40

In [55]:
# grab sections
arr_2d[:2,1:] # first argument is row 

array([[ 5, 10, 15],
       [20, 25, 30]])

In [56]:
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

In [58]:
# conditional selection
arr = np.arange(0,10)

In [59]:
arr > 5 # returns array of boolean values

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [60]:
bool_arr = arr > 5

In [61]:
arr[bool_arr] # use bool_arr to select elements when true

array([6, 7, 8, 9])

In [62]:
arr[arr>5] # conditional selection

array([6, 7, 8, 9])

In [63]:
arr_2d = np.arange(50).reshape(5,10)

In [64]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [67]:
arr_2d[1:4,3:5]

array([[13, 14],
       [23, 24],
       [33, 34]])

## Operations


In [70]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr + arr # add element by element

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [71]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
# scalers - broadcast a number to all elements
arr  + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [73]:
arr * 100 

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [74]:
arr / arr # 0/0 - nan and 1/0 - inf

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [75]:
arr **2 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

# universal array functions


In [76]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [77]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [78]:
np.max(arr)

10

In [79]:
arr.max()

10

In [80]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [81]:
np.log(arr)

/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])